name: Build and Deploy Projects

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: 'Writerside/hi'
  ARTIFACT: 'webHelpHI2-all.zip'
  DOCKER_VERSION: '241.15989'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: artifacts/${{ env.ARTIFACT }}

  test-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docs
      - uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

  deploy-docs:
    needs: test-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docs
      - run: unzip -O UTF-8 -qq '${{ env.ARTIFACT }}' -d dir
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dir
      - uses: actions/deploy-pages@v4
        id: deployment

  build-vue-chart:
    runs-on: ubuntu-latest
    needs: deploy-docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
        working-directory: ./vue-chart
      - run: npm run build
        working-directory: ./vue-chart
      - uses: actions/upload-artifact@v4
        with:
          name: vue-chart
          path: vue-chart/dist

  deploy-vue-chart:
    needs: build-vue-chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: vue-chart
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: vue-chart/dist
      - uses: actions/deploy-pages@v4
        id: deployment-vue-chart
